### PR TITLE
Add plugin feature on README

### PR DESCRIPTION
**Pull request by konifar**
## Overview

Added an easy plugin feature on README.
I referenced @zoncoen 's [slide on Merpay Tech Fest 2021](https://speakerdeck.com/mercari/merpay-tech-fest-2021-scenario-based-integration-testing-platform-for-microservices?slide=28)

If you want to modify the contents, feel free to comment please! 🙏

### CODE REVIEW

**Comment by zoncoen** [comment]
Thank you for your contribution!
Sorry for the lack of documentation. I'll write more.

BTW, I implemented a new sub-command to build plugins easier. If it's convenient for you, would you try it?
https://github.com/zoncoen/scenarigo/pull/140

You can install it by the following command.

**Comment by konifar** [comment]
> Sorry for the lack of documentation.

Never mind! This is OSS 😉 

> I plan to add a new sub-command scenarigo plugin build to build plugins easier.

Cool! I'll try its new command.
When you release this command, I'll update README again. Okay?

**Comment by zoncoen** [comment]
> When you release this command, I'll update README again. Okay?

Sure! Thank you for your kind contribution! 🙏

**Comment by zoncoen** [comment]
It seems to work well in our use cases, so I merged the PR. Feel free to ask me if you have questions. 😃 
https://github.com/zoncoen/scenarigo/pull/140

**Comment by konifar** [comment]
Thanks! It works well!!
I have one feature suggestion 🙋  I know it's not mandatory but useful for my use case.
https://github.com/zoncoen/scenarigo/issues/145

**Comment by zoncoen** [comment]
I wrote the document for the plugin feature. 🙏 https://github.com/zoncoen/scenarigo#plugin

**Pull request closed without merging**
